/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package basictutorial;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2021-10-27")
public class Storage implements org.apache.thrift.TBase<Storage, Storage._Fields>, java.io.Serializable, Cloneable, Comparable<Storage> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Storage");

  private static final org.apache.thrift.protocol.TField NUM_PUT_FIELD_DESC = new org.apache.thrift.protocol.TField("numPut", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new StorageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new StorageTupleSchemeFactory());
  }

  public int numPut; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NUM_PUT((short)1, "numPut");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NUM_PUT
          return NUM_PUT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NUMPUT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NUM_PUT, new org.apache.thrift.meta_data.FieldMetaData("numPut", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Storage.class, metaDataMap);
  }

  public Storage() {
    this.numPut = 0;

  }

  public Storage(
    int numPut)
  {
    this();
    this.numPut = numPut;
    setNumPutIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Storage(Storage other) {
    __isset_bitfield = other.__isset_bitfield;
    this.numPut = other.numPut;
  }

  public Storage deepCopy() {
    return new Storage(this);
  }

  @Override
  public void clear() {
    this.numPut = 0;

  }

  public int getNumPut() {
    return this.numPut;
  }

  public Storage setNumPut(int numPut) {
    this.numPut = numPut;
    setNumPutIsSet(true);
    return this;
  }

  public void unsetNumPut() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NUMPUT_ISSET_ID);
  }

  /** Returns true if field numPut is set (has been assigned a value) and false otherwise */
  public boolean isSetNumPut() {
    return EncodingUtils.testBit(__isset_bitfield, __NUMPUT_ISSET_ID);
  }

  public void setNumPutIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NUMPUT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NUM_PUT:
      if (value == null) {
        unsetNumPut();
      } else {
        setNumPut((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NUM_PUT:
      return getNumPut();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NUM_PUT:
      return isSetNumPut();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Storage)
      return this.equals((Storage)that);
    return false;
  }

  public boolean equals(Storage that) {
    if (that == null)
      return false;

    boolean this_present_numPut = true;
    boolean that_present_numPut = true;
    if (this_present_numPut || that_present_numPut) {
      if (!(this_present_numPut && that_present_numPut))
        return false;
      if (this.numPut != that.numPut)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_numPut = true;
    list.add(present_numPut);
    if (present_numPut)
      list.add(numPut);

    return list.hashCode();
  }

  @Override
  public int compareTo(Storage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetNumPut()).compareTo(other.isSetNumPut());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNumPut()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.numPut, other.numPut);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Storage(");
    boolean first = true;

    sb.append("numPut:");
    sb.append(this.numPut);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StorageStandardSchemeFactory implements SchemeFactory {
    public StorageStandardScheme getScheme() {
      return new StorageStandardScheme();
    }
  }

  private static class StorageStandardScheme extends StandardScheme<Storage> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Storage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NUM_PUT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.numPut = iprot.readI32();
              struct.setNumPutIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Storage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(NUM_PUT_FIELD_DESC);
      oprot.writeI32(struct.numPut);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StorageTupleSchemeFactory implements SchemeFactory {
    public StorageTupleScheme getScheme() {
      return new StorageTupleScheme();
    }
  }

  private static class StorageTupleScheme extends TupleScheme<Storage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Storage struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetNumPut()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetNumPut()) {
        oprot.writeI32(struct.numPut);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Storage struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.numPut = iprot.readI32();
        struct.setNumPutIsSet(true);
      }
    }
  }

}

